import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import '@/styles/globals.css';

import Header from '@/components/Header/Header';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
